/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

/* bluerov2_expl_vde_adj:(i0[12],i1[12],i2[8],i3[0])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a01=sin(a00);
  a02=-2.;
  a03=arg[0]? arg[0][4] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=3.8358119071273220e-02;
  a07=arg[1]? arg[1][8] : 0;
  a06=(a06*a07);
  a07=(a05*a06);
  a07=(a01*a07);
  a00=cos(a00);
  a08=2.2559999999999998e+00;
  a09=(a08*a04);
  a10=3.5982346663822264e+00;
  a11=arg[1]? arg[1][9] : 0;
  a10=(a10*a11);
  a12=3.4197956755051100e-02;
  a13=arg[1]? arg[1][7] : 0;
  a14=(a12*a13);
  a10=(a10+a14);
  a09=(a09*a10);
  a09=(a00*a09);
  a07=(a07-a09);
  a12=(a12*a11);
  a11=4.1647163856912243e-02;
  a11=(a11*a13);
  a12=(a12+a11);
  a05=(a05*a12);
  a05=(a00*a05);
  a07=(a07-a05);
  a05=arg[0]? arg[0][11] : 0;
  a11=arg[1]? arg[1][5] : 0;
  a13=(a05*a11);
  a09=(a13/a04);
  a14=arg[0]? arg[0][10] : 0;
  a15=arg[1]? arg[1][4] : 0;
  a16=(a14*a15);
  a09=(a09+a16);
  a16=tan(a03);
  a17=arg[1]? arg[1][3] : 0;
  a18=(a05*a17);
  a19=(a16*a18);
  a09=(a09+a19);
  a09=(a01*a09);
  a07=(a07-a09);
  a09=(a14*a11);
  a19=(a09/a04);
  a20=(a05*a15);
  a19=(a19-a20);
  a20=(a14*a17);
  a21=(a16*a20);
  a19=(a19+a21);
  a19=(a00*a19);
  a07=(a07+a19);
  a19=arg[0]? arg[0][8] : 0;
  a21=arg[1]? arg[1][2] : 0;
  a22=(a19*a21);
  a23=(a04*a22);
  a03=sin(a03);
  a24=arg[0]? arg[0][5] : 0;
  a25=sin(a24);
  a26=(a03*a25);
  a27=arg[1]? arg[1][1] : 0;
  a28=(a19*a27);
  a29=(a26*a28);
  a23=(a23+a29);
  a24=cos(a24);
  a29=arg[0]? arg[0][7] : 0;
  a30=(a29*a27);
  a31=(a24*a30);
  a23=(a23+a31);
  a31=(a03*a24);
  a32=arg[1]? arg[1][0] : 0;
  a33=(a19*a32);
  a34=(a31*a33);
  a23=(a23+a34);
  a34=(a29*a32);
  a35=(a25*a34);
  a23=(a23-a35);
  a23=(a01*a23);
  a07=(a07-a23);
  a23=(a29*a21);
  a35=(a04*a23);
  a36=(a24*a28);
  a35=(a35-a36);
  a36=(a25*a30);
  a37=(a03*a36);
  a35=(a35+a37);
  a37=(a25*a33);
  a35=(a35+a37);
  a37=(a24*a34);
  a38=(a03*a37);
  a35=(a35+a38);
  a35=(a00*a35);
  a07=(a07+a35);
  if (res[0]!=0) res[0][3]=a07;
  a07=(a00*a06);
  a07=(a02*a07);
  a07=(a03*a07);
  a35=(a01*a10);
  a35=(a08*a35);
  a35=(a03*a35);
  a07=(a07+a35);
  a35=(a01*a12);
  a02=(a02*a35);
  a02=(a03*a02);
  a07=(a07+a02);
  a02=3.6102613992053616e+00;
  a35=arg[1]? arg[1][10] : 0;
  a02=(a02*a35);
  a38=-4.8844425727921199e-02;
  a39=arg[1]? arg[1][6] : 0;
  a38=(a38*a39);
  a02=(a02+a38);
  a08=(a08*a02);
  a08=(a04*a08);
  a07=(a07-a08);
  a08=2.;
  a38=-4.8844425727921206e-02;
  a38=(a38*a35);
  a35=5.9484015853872731e-02;
  a35=(a35*a39);
  a38=(a38+a35);
  a08=(a08*a38);
  a08=(a04*a08);
  a07=(a07-a08);
  a08=(a00/a04);
  a35=(a08/a04);
  a35=(a35*a13);
  a13=(a01/a04);
  a39=(a13/a04);
  a39=(a39*a09);
  a35=(a35+a39);
  a35=(a03*a35);
  a07=(a07+a35);
  a18=(a00*a18);
  a20=(a01*a20);
  a18=(a18+a20);
  a20=casadi_sq(a04);
  a18=(a18/a20);
  a07=(a07+a18);
  a18=(a00*a28);
  a20=(a25*a18);
  a35=arg[0]? arg[0][6] : 0;
  a39=(a35*a21);
  a20=(a20-a39);
  a36=(a01*a36);
  a20=(a20+a36);
  a36=(a00*a33);
  a39=(a24*a36);
  a20=(a20+a39);
  a37=(a01*a37);
  a20=(a20+a37);
  a20=(a04*a20);
  a07=(a07+a20);
  a22=(a00*a22);
  a23=(a01*a23);
  a22=(a22+a23);
  a23=(a35*a27);
  a20=(a25*a23);
  a22=(a22+a20);
  a20=(a35*a32);
  a37=(a24*a20);
  a22=(a22+a37);
  a22=(a03*a22);
  a07=(a07-a22);
  if (res[0]!=0) res[0][4]=a07;
  a18=(a03*a18);
  a07=(a01*a03);
  a22=(a07*a30);
  a18=(a18+a22);
  a23=(a04*a23);
  a18=(a18+a23);
  a33=(a01*a33);
  a18=(a18+a33);
  a33=(a00*a34);
  a18=(a18-a33);
  a18=(a24*a18);
  a30=(a00*a30);
  a28=(a01*a28);
  a30=(a30-a28);
  a36=(a03*a36);
  a30=(a30+a36);
  a34=(a07*a34);
  a30=(a30+a34);
  a20=(a04*a20);
  a30=(a30+a20);
  a30=(a25*a30);
  a18=(a18-a30);
  if (res[0]!=0) res[0][5]=a18;
  a18=(a25*a04);
  a18=(a18*a27);
  a30=4.0300000000000002e+00;
  a20=1.8180000000000000e+01;
  a34=casadi_fabs(a35);
  a34=(a20*a34);
  a30=(a30+a34);
  a30=(a30*a38);
  a34=casadi_sign(a35);
  a35=(a35*a38);
  a20=(a20*a35);
  a34=(a34*a20);
  a30=(a30+a34);
  a03=(a03*a21);
  a30=(a30+a03);
  a18=(a18-a30);
  a30=(a24*a04);
  a30=(a30*a32);
  a18=(a18+a30);
  if (res[0]!=0) res[0][6]=a18;
  a18=(a01*a04);
  a18=(a18*a21);
  a30=6.2199999999999998e+00;
  a03=2.1660000000000000e+01;
  a34=casadi_fabs(a29);
  a34=(a03*a34);
  a30=(a30+a34);
  a30=(a30*a12);
  a34=casadi_sign(a29);
  a29=(a29*a12);
  a03=(a03*a29);
  a34=(a34*a03);
  a30=(a30+a34);
  a18=(a18-a30);
  a30=(a24*a00);
  a34=(a07*a25);
  a30=(a30+a34);
  a30=(a30*a27);
  a18=(a18+a30);
  a07=(a07*a24);
  a30=(a25*a00);
  a07=(a07-a30);
  a07=(a07*a32);
  a18=(a18+a07);
  if (res[0]!=0) res[0][7]=a18;
  a04=(a00*a04);
  a04=(a04*a21);
  a21=5.1799999999999997e+00;
  a18=3.6990000000000002e+01;
  a07=casadi_fabs(a19);
  a07=(a18*a07);
  a21=(a21+a07);
  a21=(a21*a06);
  a07=casadi_sign(a19);
  a19=(a19*a06);
  a18=(a18*a19);
  a07=(a07*a18);
  a21=(a21+a07);
  a04=(a04-a21);
  a26=(a26*a00);
  a24=(a24*a01);
  a26=(a26-a24);
  a26=(a26*a27);
  a04=(a04+a26);
  a25=(a25*a01);
  a31=(a31*a00);
  a25=(a25+a31);
  a25=(a25*a32);
  a04=(a04+a25);
  if (res[0]!=0) res[0][8]=a04;
  a04=7.0000000000000007e-02;
  a25=1.5500000000000000e+00;
  a32=arg[0]? arg[0][9] : 0;
  a31=casadi_fabs(a32);
  a31=(a25*a31);
  a31=(a04+a31);
  a31=(a31*a10);
  a26=casadi_sign(a32);
  a32=(a32*a10);
  a32=(a25*a32);
  a26=(a26*a32);
  a31=(a31+a26);
  a31=(a17-a31);
  if (res[0]!=0) res[0][9]=a31;
  a13=(a13*a11);
  a31=casadi_fabs(a14);
  a31=(a25*a31);
  a31=(a04+a31);
  a31=(a31*a02);
  a26=casadi_sign(a14);
  a14=(a14*a02);
  a14=(a25*a14);
  a26=(a26*a14);
  a31=(a31+a26);
  a13=(a13-a31);
  a31=(a00*a15);
  a13=(a13+a31);
  a31=(a01*a16);
  a31=(a31*a17);
  a13=(a13+a31);
  if (res[0]!=0) res[0][10]=a13;
  a08=(a08*a11);
  a11=casadi_fabs(a05);
  a11=(a25*a11);
  a04=(a04+a11);
  a11=3.5701535166012137e+00;
  a13=arg[1]? arg[1][11] : 0;
  a11=(a11*a13);
  a04=(a04*a11);
  a13=casadi_sign(a05);
  a05=(a05*a11);
  a25=(a25*a05);
  a13=(a13*a25);
  a04=(a04+a13);
  a08=(a08-a04);
  a01=(a01*a15);
  a08=(a08-a01);
  a00=(a00*a16);
  a00=(a00*a17);
  a08=(a08+a00);
  if (res[0]!=0) res[0][11]=a08;
  a08=-1.8880000000000000e-01;
  a08=(a08*a11);
  a00=5.9999999999999998e-02;
  a17=(a00*a10);
  a16=(a08+a17);
  a01=-7.0699999999999996e-01;
  a15=(a01*a12);
  a16=(a16+a15);
  a00=(a00*a02);
  a16=(a16+a00);
  a04=7.0699999999999996e-01;
  a13=(a04*a38);
  a16=(a16+a13);
  if (res[0]!=0) res[0][12]=a16;
  a16=1.8880000000000000e-01;
  a16=(a16*a11);
  a11=-5.9999999999999998e-02;
  a25=(a11*a10);
  a05=(a16+a25);
  a04=(a04*a12);
  a05=(a05+a04);
  a05=(a05+a00);
  a05=(a05+a13);
  if (res[0]!=0) res[0][13]=a05;
  a16=(a16+a17);
  a16=(a16+a15);
  a11=(a11*a02);
  a16=(a16+a11);
  a01=(a01*a38);
  a16=(a16+a01);
  if (res[0]!=0) res[0][14]=a16;
  a08=(a08+a25);
  a08=(a08+a04);
  a08=(a08+a11);
  a08=(a08+a01);
  if (res[0]!=0) res[0][15]=a08;
  a08=-2.1800000000000000e-01;
  a08=(a08*a10);
  a01=(a08-a06);
  a11=1.2000000000000000e-01;
  a11=(a11*a02);
  a01=(a01+a11);
  if (res[0]!=0) res[0][16]=a01;
  a08=(a06+a08);
  a01=-1.2000000000000000e-01;
  a01=(a01*a02);
  a08=(a08+a01);
  if (res[0]!=0) res[0][17]=a08;
  a08=2.1800000000000000e-01;
  a08=(a08*a10);
  a10=(a06+a08);
  a10=(a10+a11);
  if (res[0]!=0) res[0][18]=a10;
  a08=(a08-a06);
  a08=(a08+a01);
  if (res[0]!=0) res[0][19]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
