/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* bluerov2_expl_ode_fun:(i0[12],i1[8],i2[0])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[0]? arg[0][5] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[0]? arg[0][6] : 0;
  a04=(a04*a05);
  a06=arg[0]? arg[0][3] : 0;
  a07=sin(a06);
  a08=sin(a02);
  a09=(a07*a08);
  a10=(a09*a01);
  a00=sin(a00);
  a06=cos(a06);
  a11=(a00*a06);
  a10=(a10-a11);
  a11=arg[0]? arg[0][7] : 0;
  a10=(a10*a11);
  a04=(a04+a10);
  a10=(a00*a07);
  a12=(a08*a01);
  a12=(a12*a06);
  a10=(a10+a12);
  a12=arg[0]? arg[0][8] : 0;
  a10=(a10*a12);
  a04=(a04+a10);
  if (res[0]!=0) res[0][0]=a04;
  a04=(a00*a03);
  a04=(a04*a05);
  a10=(a01*a06);
  a09=(a09*a00);
  a10=(a10+a09);
  a10=(a10*a11);
  a04=(a04+a10);
  a00=(a08*a00);
  a00=(a00*a06);
  a01=(a01*a07);
  a00=(a00-a01);
  a00=(a00*a12);
  a04=(a04+a00);
  if (res[0]!=0) res[0][1]=a04;
  a04=(a07*a03);
  a04=(a04*a11);
  a00=(a08*a05);
  a04=(a04-a00);
  a00=(a06*a03);
  a00=(a00*a12);
  a04=(a04+a00);
  if (res[0]!=0) res[0][2]=a04;
  a04=arg[0]? arg[0][9] : 0;
  a02=tan(a02);
  a00=(a07*a02);
  a01=arg[0]? arg[0][10] : 0;
  a00=(a00*a01);
  a00=(a04+a00);
  a02=(a06*a02);
  a10=arg[0]? arg[0][11] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  if (res[0]!=0) res[0][3]=a00;
  a00=(a06*a01);
  a02=(a07*a10);
  a00=(a00-a02);
  if (res[0]!=0) res[0][4]=a00;
  a00=(a07/a03);
  a00=(a00*a01);
  a02=(a06/a03);
  a02=(a02*a10);
  a00=(a00+a02);
  if (res[0]!=0) res[0][5]=a00;
  a00=5.9484015853872731e-02;
  a02=7.0699999999999996e-01;
  a09=arg[1]? arg[1][0] : 0;
  a13=(a02*a09);
  a14=arg[1]? arg[1][1] : 0;
  a15=(a02*a14);
  a13=(a13+a15);
  a16=-7.0699999999999996e-01;
  a17=arg[1]? arg[1][2] : 0;
  a18=(a16*a17);
  a13=(a13+a18);
  a19=arg[1]? arg[1][3] : 0;
  a20=(a16*a19);
  a13=(a13+a20);
  a20=4.0300000000000002e+00;
  a21=1.8180000000000000e+01;
  a22=casadi_fabs(a05);
  a21=(a21*a22);
  a20=(a20+a21);
  a20=(a20*a05);
  a13=(a13-a20);
  a20=2.;
  a20=(a20*a08);
  a13=(a13-a20);
  a00=(a00*a13);
  a20=-4.8844425727921199e-02;
  a05=5.9999999999999998e-02;
  a21=(a05*a09);
  a22=(a05*a14);
  a22=(a21+a22);
  a23=-5.9999999999999998e-02;
  a24=(a23*a17);
  a22=(a22+a24);
  a24=(a23*a19);
  a22=(a22+a24);
  a25=1.2000000000000000e-01;
  a26=arg[1]? arg[1][4] : 0;
  a27=(a25*a26);
  a22=(a22+a27);
  a27=-1.2000000000000000e-01;
  a28=arg[1]? arg[1][5] : 0;
  a29=(a27*a28);
  a22=(a22+a29);
  a29=arg[1]? arg[1][6] : 0;
  a25=(a25*a29);
  a22=(a22+a25);
  a25=arg[1]? arg[1][7] : 0;
  a27=(a27*a25);
  a22=(a22+a27);
  a27=7.0000000000000007e-02;
  a30=1.5500000000000000e+00;
  a31=casadi_fabs(a01);
  a31=(a30*a31);
  a31=(a27+a31);
  a31=(a31*a01);
  a22=(a22-a31);
  a31=2.2559999999999998e+00;
  a08=(a31*a08);
  a22=(a22-a08);
  a20=(a20*a22);
  a00=(a00+a20);
  if (res[0]!=0) res[0][6]=a00;
  a00=4.1647163856912243e-02;
  a16=(a16*a09);
  a16=(a16+a15);
  a16=(a16+a18);
  a02=(a02*a19);
  a16=(a16+a02);
  a02=6.2199999999999998e+00;
  a18=2.1660000000000000e+01;
  a15=casadi_fabs(a11);
  a18=(a18*a15);
  a02=(a02+a18);
  a02=(a02*a11);
  a16=(a16-a02);
  a02=-2.;
  a02=(a02*a03);
  a11=(a02*a07);
  a16=(a16-a11);
  a00=(a00*a16);
  a11=3.4197956755051100e-02;
  a23=(a23*a14);
  a21=(a21+a23);
  a05=(a05*a17);
  a21=(a21+a05);
  a21=(a21+a24);
  a24=-2.1800000000000000e-01;
  a05=(a24*a26);
  a21=(a21+a05);
  a24=(a24*a28);
  a21=(a21+a24);
  a24=2.1800000000000000e-01;
  a05=(a24*a29);
  a21=(a21+a05);
  a24=(a24*a25);
  a21=(a21+a24);
  a24=casadi_fabs(a04);
  a24=(a30*a24);
  a24=(a27+a24);
  a24=(a24*a04);
  a21=(a21-a24);
  a31=(a31*a03);
  a31=(a31*a07);
  a21=(a21-a31);
  a31=(a11*a21);
  a00=(a00+a31);
  if (res[0]!=0) res[0][7]=a00;
  a00=3.8358119071273220e-02;
  a28=(a28-a26);
  a28=(a28+a29);
  a28=(a28-a25);
  a25=5.1799999999999997e+00;
  a29=3.6990000000000002e+01;
  a26=casadi_fabs(a12);
  a29=(a29*a26);
  a25=(a25+a29);
  a25=(a25*a12);
  a28=(a28-a25);
  a02=(a02*a06);
  a28=(a28-a02);
  a00=(a00*a28);
  if (res[0]!=0) res[0][8]=a00;
  a11=(a11*a16);
  a16=3.5982346663822264e+00;
  a16=(a16*a21);
  a11=(a11+a16);
  if (res[0]!=0) res[0][9]=a11;
  a11=-4.8844425727921206e-02;
  a11=(a11*a13);
  a13=3.6102613992053616e+00;
  a13=(a13*a22);
  a11=(a11+a13);
  if (res[0]!=0) res[0][10]=a11;
  a11=3.5701535166012137e+00;
  a13=-1.8880000000000000e-01;
  a09=(a13*a09);
  a22=1.8880000000000000e-01;
  a14=(a22*a14);
  a09=(a09+a14);
  a22=(a22*a17);
  a09=(a09+a22);
  a13=(a13*a19);
  a09=(a09+a13);
  a13=casadi_fabs(a10);
  a30=(a30*a13);
  a27=(a27+a30);
  a27=(a27*a10);
  a09=(a09-a27);
  a11=(a11*a09);
  if (res[0]!=0) res[0][11]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
